/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apply } from '../fn/loan-app-controller/apply';
import { Apply$Params } from '../fn/loan-app-controller/apply';
import { approve } from '../fn/loan-app-controller/approve';
import { Approve$Params } from '../fn/loan-app-controller/approve';
import { LoanApp } from '../models/loan-app';

@Injectable({ providedIn: 'root' })
export class LoanAppControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `approve()` */
  static readonly ApprovePath = '/loan/approve';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `approve()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  approve$Response(params: Approve$Params, context?: HttpContext): Observable<StrictHttpResponse<LoanApp>> {
    return approve(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `approve$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  approve(params: Approve$Params, context?: HttpContext): Observable<LoanApp> {
    return this.approve$Response(params, context).pipe(
      map((r: StrictHttpResponse<LoanApp>): LoanApp => r.body)
    );
  }

  /** Path part for operation `apply()` */
  static readonly ApplyPath = '/loan/apply';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apply()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  apply$Response(params: Apply$Params, context?: HttpContext): Observable<StrictHttpResponse<LoanApp>> {
    return apply(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apply$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  apply(params: Apply$Params, context?: HttpContext): Observable<LoanApp> {
    return this.apply$Response(params, context).pipe(
      map((r: StrictHttpResponse<LoanApp>): LoanApp => r.body)
    );
  }

}
