/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AssetDto {
  acquisitionDate?: string;
  assetType?: 'REAL_ESTATE' | 'VEHICLE' | 'INVESTMENT';
  estimatedValue?: number;
}
