/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface Asset {
  acquisitionDate?: string;
  assetType?: 'REAL_ESTATE' | 'VEHICLE' | 'INVESTMENT';
  estimatedValue?: number;
  id?: number;
  owner?: User;
}
