/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AssetResponseDto {
  acquisitionDate?: string;
  assetType?: string;
  estimatedValue?: number;
  id?: number;
  ownerFirstName?: string;
  ownerLastName?: string;
}
