/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BankAccount } from '../models/bank-account';
export interface Bank {
  bankaccounts?: Array<BankAccount>;
  basicLimit?: number;
  bic?: string;
  id?: number;
  name?: string;
}
