/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BankAccountDto {
  ClientFirstName?: string;
  ClientLastName?: string;
  accountNumber?: string;
  balance?: number;
  bankAccountType?: string;
  id?: number;
  isActive?: boolean;
}
