/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Bank } from '../models/bank';
import { User } from '../models/user';
export interface BankAccount {
  accountNumber?: string;
  active?: boolean;
  balance?: number;
  bank?: Bank;
  bankAccountType?: 'Current' | 'Savings' | 'ForeignCurrency' | 'Youth' | 'Joint' | 'Business';
  client?: User;
  id?: number;
}
