/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface LoanApp {
  amount?: number;
  approved?: boolean;
  approvedAt?: string;
  approvedBy?: User;
  client?: User;
  createdAt?: string;
  id?: number;
  loanType?: 'PERSONAL' | 'MORTGAGE' | 'AUTO' | 'BUSINESS' | 'STUDENT';
}
