/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Role } from '../models/role';
export interface Permission {
  id?: number;
  name?: 'MANAGE_USERS' | 'FULL_ACCESS' | 'APPROVE_TRANSACTIONS' | 'VIEW_ALL_ACCOUNTS' | 'MANAGE_OWN_ACCOUNT' | 'VIEW_OWN_ACCOUNT';
  roles?: Array<Role>;
}
