/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Role } from '../models/role';
export interface RegisterRequest {
  age?: number;
  email?: string;
  firstName?: string;
  lastName?: string;
  password?: string;
  phone?: string;
  role?: Role;
}
