/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Permission } from '../models/permission';
import { SimpleGrantedAuthority } from '../models/simple-granted-authority';
import { User } from '../models/user';
export interface Role {
  authorities?: Array<SimpleGrantedAuthority>;
  id?: number;
  name?: 'CLIENT' | 'ADMIN' | 'EMPLOYEE';
  permissions?: Array<Permission>;
  users?: Array<User>;
}
