/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RecurringDetails } from '../models/recurring-details';
export interface TransactionRequestDto {
  accountNumber?: string;
  amount: number;
  recurringDetails?: RecurringDetails;
  transactionType?: 'CLASSIC' | 'INSTANT' | 'PERMANENT';
}
