/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Asset } from '../models/asset';
import { BankAccount } from '../models/bank-account';
import { GrantedAuthority } from '../models/granted-authority';
import { Role } from '../models/role';
export interface User {
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
  age?: number;
  assets?: Array<Asset>;
  authorities?: Array<GrantedAuthority>;
  bankAccounts?: Array<BankAccount>;
  credentialsNonExpired?: boolean;
  email?: string;
  enabled?: boolean;
  firstName?: string;
  id?: number;
  lastName?: string;
  memberSince?: string;
  password?: string;
  phone?: string;
  role?: Role;
  username?: string;
}
