/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Bank } from '../../models/bank';

export interface CreateBank$Params {
      body: Bank
}

export function createBank(http: HttpClient, rootUrl: string, params: CreateBank$Params, context?: HttpContext): Observable<StrictHttpResponse<Bank>> {
  const rb = new RequestBuilder(rootUrl, createBank.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Bank>;
    })
  );
}

createBank.PATH = '/banks';
