/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Bank } from '../../models/bank';

export interface GetAllBanks$Params {
}

export function getAllBanks(http: HttpClient, rootUrl: string, params?: GetAllBanks$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Bank>>> {
  const rb = new RequestBuilder(rootUrl, getAllBanks.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Bank>>;
    })
  );
}

getAllBanks.PATH = '/banks';
