
### ALL ACCOUNTS
GET  http://localhost:8080/api/bankaccounts

### FIND BY ID
GET http://localhost:8080/api/bankaccounts/2

### FIND BY ID THAT DOESNT EXIST
GET http://localhost:8080/api/bankaccounts/99

### CREATE ACCOUNT
POST http://localhost:8080/api/bankaccounts
Content-Type: application/json

{
  "accountNumber": "ST3434",
  "balance": 1000.00,
  "isActive": true
}

### UPDATE ACCOUNT

PUT http://localhost:8080/api/bankaccounts/2
Content-Type: application/json

{
  "id": 2,
  "accountNumber": "ZAERTZ",
  "balance": 1000.00,
  "isActive": false
}




