/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Asset } from '../../models/asset';

export interface UpdateAsset$Params {
  id: number;
      body: Asset
}

export function updateAsset(http: HttpClient, rootUrl: string, params: UpdateAsset$Params, context?: HttpContext): Observable<StrictHttpResponse<Asset>> {
  const rb = new RequestBuilder(rootUrl, updateAsset.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Asset>;
    })
  );
}

updateAsset.PATH = '/assets/{id}';
